# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = true

  # Use username/password instead of SSH key
  config.ssh.insert_key = false
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  # Ubuntu clients
  (1..3).each do |i|
    config.vm.define "ubuntu#{i}", autostart: true do |node|
      node.vm.box = "bento/ubuntu-22.04"
      node.vm.hostname = "ubuntu#{i}"
      node.vm.network "public_network", ip: "192.168.0.#{10+i}"
      node.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"] = "1024"
        v.vmx["numvcpus"] = "1"
        v.gui = true
      end

      # Provision the VM
      node.vm.provision "shell", path: "provision_ubuntu.sh"
    end
  end
end